version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - '${BACKEND_PORT}:10000'
    restart: always
    networks:
      - front
      - back
    environment:
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD={POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - SECRET=${SECRET}
      - ENV=prod
      - HOST=${HOST}
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '${FRONTEND_PORT}:3000'
    depends_on:
      - backend
    restart: always
    environment:
      - NEXT_APP_URL=127.0.0.1:3000
      - NET_APP_SERVER_URL=backend
      - NET_APP_ENV=development

networks:
  front:
    driver: bridge
  back:
    driver: bridge
